version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: backend-node-app
    # platform: linux/amd64  # Specify the platform
    container_name: node-dev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules  # Ensures node_modules is not overwritten by the host
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    depends_on:
      - db
    ports:
      - "4200:4200"
    command: npm run-script start-dev

  db:
    image: mysql:5.7
    # platform: linux/amd64  # Specify the platform
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./ngnix.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/api.theshopbusiness.com.pem:/etc/nginx/ssl/certificate.pem
      - ./ssl/api.theshopbusiness.com.key:/etc/nginx/ssl/private.key
    # volumes:
    #   - ./ngnix.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

volumes:
  db-data:


  # sudo docker-compose --env-file ./env/.env.dev -f docker-compose-dev.yml up -d
