version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-dev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules  # Ensures node_modules is not overwritten by the host
    env_file:
      - ./env/.env.dev  # 
    depends_on:
      - mysql
    ports:
      - "4200:4200"
    # command: npm install && npm run-script start-dev

  mysql:
    image: mysql:5.7
    # platform: linux/amd64  # Specify the platform
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./sql_script.sql:/docker-entrypoint-initdb.d/init.sql


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ngnix.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/certificate.crt:/etc/ssl/certificate.crt
      - ./ssl/private.key:/etc/ssl/private.key
    # volumes:
    #   - ./ngnix.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

volumes:
  db-data:


  # sudo docker-compose --env-file ./env/.env.dev -f docker-compose-dev.yml up -d
  # sudo docker run -it --rm   -v $(pwd)/certs:/etc/letsencrypt   -v $(pwd)/certs-data:/data/letsencrypt   certbot/certbot certonly   --webroot   -w /data/letsencrypt   --email nikhil@theshopbusiness.com   -d api.theshopbusiness.com   --agree-tos   --no-eff-email -v
  # ssh -i LightsailDefaultKey-us-east-1\(3\).pem ubuntu@44.214.135.221  